import type { Camera } from "../gfx/graphics"
import type { GameMap } from "../map/map"
import type { Sprite } from "../mesh/sprite"
import type { Chaingun, GameContext } from "./types"

export const ctx: GameContext = {
  gl: null as unknown as WebGL2RenderingContext,
  map: null as unknown as GameMap,
  objects: [],
  walls: [],
  camera: null as unknown as Camera,
  realCamera: (tex) => tex,
  lights: [],
  cameraShake: 0,
  program1: null as unknown as WebGLProgram,
  program2: null as unknown as WebGLProgram,
  locations: {},
  locations1: {},
  locations2: {},
  keys: {},
  canPlayMusic: false,
  pageHasFocus: true,
  endScreen: false,
  difficulty: 0,
  graphics: 0,
  lastNow: 0,
  moved: 0,
  lastGunshot: 0,
  speed: 0,
  globalScreenColor: [0, 0, 0, 1],
  playerDead: false,
  health: 5,
  goingBack: false,
  lightIsHeld: false,
  frame: 0,
  framecount: 0,
  minorBadness: 0,
  totalBadness: 0,
  lightId: 0,
  allTextures: [],
  chaingun: null as unknown as Chaingun,
  myBody: null as unknown as Sprite,
  lastUserHit: 0,
  sounds: {},
  musicTimeouts: [],
  musicNotes: null,
}
